name: cicd
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: print-vars
        run: env
      - name: sanitize-ref-name
        id: sanitize
        run: 'echo "::set-output name=sanitized-ref-name::$(echo $GITHUB_REF_NAME | sed -r ''s/([^a-zA-Z0-9.]+)/-/g'' | sed -r ''s/(^-|-$)//g'')"'
      - name: print-sanitizef-ref-name
        run: echo ${{ steps.sanitize.outputs.sanitized-ref-name }}
      - name: build-commons
        run: docker buildx build -f Dockerfile.common -t metas-mvn-common:latest .
      - name: build-backend
        env:
          mysecret: ${{ secrets.TESTMO_TOKEN }}
        run: docker buildx build -f Dockerfile.backend --secret id=mysecret --build-arg REFNAME=${{ steps.sanitize.outputs.sanitized-ref-name }} -t metas-mvn-backend:latest .
      - name: build-camel
        run: docker buildx build -f Dockerfile.camel -t metas-mvn-camel:latest .
      - name: build-cucumber
        run: docker buildx build -f Dockerfile.cucumber --build-arg REFNAME=${{ steps.sanitize.outputs.sanitized-ref-name }} -t metas-cucumber:latest .

      - name: build-api
        run: docker buildx build -f Dockerfile.backend.api -t mazorn/metas-api:${{ steps.sanitize.outputs.sanitized-ref-name }} -t mazorn/metas-api:${{ steps.sanitize.outputs.sanitized-ref-name }}-$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT .
      - name: build-app
        run: docker buildx build -f Dockerfile.backend.app -t mazorn/metas-app:${{ steps.sanitize.outputs.sanitized-ref-name }} -t mazorn/metas-app:${{ steps.sanitize.outputs.sanitized-ref-name }}-$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT .
      - name: build-externalsystems
        run: docker buildx build -f Dockerfile.camel.externalsystems -t metas-externalsystems:${{ steps.sanitize.outputs.sanitized-ref-name }} .
      - name: build-frontend
        run: docker buildx build -f Dockerfile.frontend -t mazorn/metas-frontend:${{ steps.sanitize.outputs.sanitized-ref-name }} -t mazorn/metas-frontend:${{ steps.sanitize.outputs.sanitized-ref-name }}-$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT .
      - name: build-mobile
        run: docker buildx build -f Dockerfile.mobile -t mazorn/metas-mobile:${{ steps.sanitize.outputs.sanitized-ref-name }} -t mazorn/metas-mobile:${{ steps.sanitize.outputs.sanitized-ref-name }}-$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT .
      - name: build-db
        run: docker buildx build -f Dockerfile.db-standalone -t metas-db:latest -t mazorn/metas-db:${{ steps.sanitize.outputs.sanitized-ref-name }} -t mazorn/metas-db:${{ steps.sanitize.outputs.sanitized-ref-name }}-$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT .
      - name: build-db-preloaded
        run: docker buildx build -f Dockerfile.db-preloaded -t metas-db:preloaded -t mazorn/metas-db:${{ steps.sanitize.outputs.sanitized-ref-name }}-preloaded -t mazorn/metas-db:${{ steps.sanitize.outputs.sanitized-ref-name }}-$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT-preloaded .

      - name: run-cucumber-tests
        env:
          mysecret: ${{ secrets.TESTMO_TOKEN }}
        run: |
          cd cucumber
          echo "$mysecret" > mysecret
          docker-compose up --abort-on-container-exit
          docker-compose down
        
      - name: push-images
        run: |
          echo ${{ secrets.DOCKERHUB_RW_TOKEN }} | docker login --username mazorn --password-stdin
          docker push mazorn/metas-api:${{ steps.sanitize.outputs.sanitized-ref-name }}-$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT
          docker push mazorn/metas-api:${{ steps.sanitize.outputs.sanitized-ref-name }}
          docker push mazorn/metas-app:${{ steps.sanitize.outputs.sanitized-ref-name }}-$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT
          docker push mazorn/metas-app:${{ steps.sanitize.outputs.sanitized-ref-name }}
          docker push mazorn/metas-frontend:${{ steps.sanitize.outputs.sanitized-ref-name }}-$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT
          docker push mazorn/metas-frontend:${{ steps.sanitize.outputs.sanitized-ref-name }}
          docker push mazorn/metas-db:${{ steps.sanitize.outputs.sanitized-ref-name }}-$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT
          docker push mazorn/metas-db:${{ steps.sanitize.outputs.sanitized-ref-name }}
          docker push mazorn/metas-db:${{ steps.sanitize.outputs.sanitized-ref-name }}-$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT-preloaded
          docker push mazorn/metas-db:${{ steps.sanitize.outputs.sanitized-ref-name }}-preloaded
          docker logout
  redeploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/mzorn/wip-local-dockerbuilds'
    steps:
      - name: remove-running-pods
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.K8S_CONFIG }}
        with:
          args: delete -n dev --all pods
