name: test
on:
  workflow_run:
    workflows: [cicd]
    types:
      - completed
  workflow_dispatch: {}

jobs:

  init:   
    runs-on: ubuntu-latest
    steps:
      - name: print-vars
        run: env
      - name: show-me-the-money
        run: echo ${{ github.event.workflow_run.head_branch }}
  cucumber:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    needs: [init, backend, frontend]
    environment: 'test'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: build-cucumber
        run: |
          docker buildx build \
          -f docker-builds/Dockerfile.cucumber \
          --build-arg REFNAME=${{ needs.init.outputs.sanitized-refname }} \
          -t metas-cucumber:latest \
          .
      - name: run-cucumber-tests
        env:
          mysecret: ${{ secrets.TESTMO_TOKEN }}
          refname: ${{ needs.init.outputs.sanitized-refname }}
        timeout-minutes: 60
        run: |
          cd cucumber
          echo "$mysecret" > mysecret
          docker-compose up --abort-on-container-exit --exit-code-from cucumber
          docker-compose down

  cypress:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    needs: [init, backend, frontend]
    environment: 'test'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: build-e2e
        run: |
          docker buildx build \
          -f docker-builds/Dockerfile.e2e \
          --build-arg REFNAME=${{ needs.init.outputs.sanitized-refname }} \
          -t metas-e2e:latest \
          .
      - name: run-cypress-tests
        env:
          mysecret: ${{ secrets.TESTMO_TOKEN }}
          refname: ${{ needs.init.outputs.sanitized-refname }}
        timeout-minutes: 120
        run: |
          cd docker-builds/e2e
          echo "$mysecret" > mysecret
          docker-compose up --abort-on-container-exit --exit-code-from e2e
          docker-compose down
